### ISSUE TITLE
Octoprint is starting - never actually starts...

### ISSUE THREAD

**Issue by jaymcd** [feelfreelinux/octo4a#20] opened 2021-06-17 19:36 UTC
Love this idea. My installation wont start though. It says it should only take a few seconds but it has been saying that for an hour now... Are there some additional permission or something I need to setup? Running on an old Asus Transformer TF300 running Katkiss Android ROM ( Android 7.1.2)

**Comment by feelfreelinux** [comment] 2021-06-18 09:49
This might be caused by a faulty install. Try to uninstall the app and install it again

**Comment by jaymcd** [comment] 2021-06-18 23:05
Ok. I will give it a try on Monday

Jay M. McDonald

________________________________

**Comment by jaymcd** [comment] 2021-06-21 16:47
Works after reinstall. Thanks. Just working to get the Camera working. What are the normal Octoprint settings for it - anything different or special?

**Comment by feelfreelinux** [comment] 2021-06-23 08:38
> Works after reinstall. Thanks. Just working to get the Camera working. What are the normal Octoprint settings for it - anything different or special?

camera should be automatically configured in octo after the start. You just need to turn it on in my app's settings.

**Comment by feelfreelinux** [comment] 2021-06-23 08:38
Closing, as looks like the issue is resolved.

**Closed by feelfreelinux** 2021-06-23 08:38 UTC
