### ISSUE TITLE
New Octoprint update breaks Octo4a - server loads on phone but web interface gives a “Loading Failed” error message repeatedly.

### ISSUE THREAD

**Issue by wezxwezx** [feelfreelinux/octo4a#204] opened 2022-05-17 20:21 UTC
Knew I shouldn’t have updated Octoprint. Server loads on phone on Octo4a, but the browser gives an error message repeatedly.

**Comment by cp2004** [comment] 2022-05-17 21:04
> Knew I shouldn’t have updated Octoprint. Server loads on phone on Octo4a, but the browser gives an error message repeatedly.

This isn't a very helpful bug report. It's no good saying 'Gives an error message', usually maintainers need to know what the error message is.... #205 is an example for you on what is helpful.

**Comment by feelfreelinux** [comment] 2022-05-17 21:09
Looking into the issue!

**Comment by wezxwezx** [comment] 2022-05-17 22:02
> > Knew I shouldn’t have updated Octoprint. Server loads on phone on Octo4a, but the browser gives an error message repeatedly.
> 
> This isn't a very helpful bug report. It's no good saying 'Gives an error message', usually maintainers need to know what the error message is.... #205 is an example for you on what is helpful.

![3643F85E-5BF5-4AEF-900E-1E835E8EB298](https://user-images.githubusercontent.com/100168786/168917441-450cd48a-3690-4534-9f6e-60e52c642570.jpeg)

**Comment by wezxwezx** [comment] 2022-05-17 22:04
> Looking into the issue!

Thank you for working on the problem…I have no idea what I was thinking upgrading without checking around to see if there would be problems! Totally stupid on my part!

**Comment by drinkspiller** [comment] 2022-05-17 22:07
@feelfreelinux — is there a way to force a (re)install of 1.7.x?

**Comment by simspace-dev** [comment] 2022-05-17 23:57
I just picked up a Pixel 3XL and just now installed Octo4a and I am getting the same error ...
<img width="1648" alt="image" src="https://user-images.githubusercontent.com/4808756/168930830-c1b58f89-d97f-4537-990e-213a1bca37a1.png">

**Comment by simspace-dev** [comment] 2022-05-18 00:11
Figured out how to email myself the logs ... Hope this helps...
[octo4a-logs.txt](https://github.com/feelfreelinux/octo4a/files/8712254/octo4a-logs.txt)

**Comment by simspace-dev** [comment] 2022-05-18 00:20
> @feelfreelinux — is there a way to force a (re)install of 1.7.x?

You can download older .apk's on the releases page:
https://github.com/feelfreelinux/octo4a/releases

**Comment by wezxwezx** [comment] 2022-05-18 01:01
> > @feelfreelinux — is there a way to force a (re)install of 1.7.x?
> 
> You can download older .apk's on the releases page: https://github.com/feelfreelinux/octo4a/releases

If we were to just reinstall an older version it would give us a different IP address than what we had before this correct?

**Comment by simspace-dev** [comment] 2022-05-18 11:46
For those experiencing this problem and find this issue, see [this post](https://github.com/feelfreelinux/octo4a/issues/205) for an update how to resolve it until a fix is released. Specifically [this post](https://github.com/feelfreelinux/octo4a/issues/205#issuecomment-1129345608).

**Comment by feelfreelinux** [comment] 2022-05-18 12:57
Duplicate of https://github.com/feelfreelinux/octo4a/issues/205

Fix released, please install version 1.1.0

**Closed by feelfreelinux** 2022-05-18 12:57 UTC
