### ISSUE TITLE
Changing values in ssh?

### ISSUE THREAD

**Issue by Eruditionis** [feelfreelinux/octo4a#184] opened 2022-03-28 21:00 UTC
Hello, I am trying to make my camera fps higher for streaming purposes, I was wondering what I need to do to access that value? No idea if I need to SSH into it, or if I can just do it somewhere in the app? Any help would be appreciated!

**Comment by alufers** [comment] 2022-10-07 00:11
Duplicate of: #221

**Closed by alufers** 2022-10-07 00:11 UTC
