### ISSUE TITLE
Octolapse using portrait mode even when rotating 90 degrees

### ISSUE THREAD

**Issue by spdecoste** [feelfreelinux/octo4a#133] opened 2022-01-02 22:01 UTC
This is probably a Octolapse issue, but I'm asking here because using a phone for octoprint is the main part of it!

I have my phone sideways. Camera is rotated 90 degrees in Control Tab and works great, 16:9 and stuff! But when I do the same with Octolapse it just keeps the 2:3 portrait mode, but the camera is in the right position.

Is there any fix to this?

**Comment by carmaselli** [comment] 2022-01-09 03:47
Yeah, go to octolapse settings. Scroll down up to "General Options" and select "Rotate 90 Degrees" in the dropdown menu. Im not sure if that will solve te aspect ratio though

**Comment by alufers** [comment] 2022-10-07 00:28
Duplicate of #279

**Closed by alufers** 2022-10-07 00:28 UTC
