### ISSUE TITLE
Application crashed on TV boxes X96max and X96mini

### ISSUE THREAD

**Issue by WEREWOLF1973** [feelfreelinux/octo4a#238] opened 2022-07-10 03:53 UTC
After installation 1st time octo server is started, can be configured and fully operational.
When i have tryed activate a USB camera, application has crashed. New launch is impossible with same error. 
Rebooting does not help.

Was tested X96max and X96mini with Android 7,9 - same result.

**Comment by infestius** [comment] 2022-07-10 07:03
Hi, same problem on a mecool m8s pro w. You Can try this : go to your Android settings / applications / octoprint / permissions/  here you can revoke camera permission and will disable camera server.
I found that camera server running always made app crash on my Android box.
Feel free to tell if it works too for you

**Comment by WEREWOLF1973** [comment] 2022-07-10 13:46
> Hi, same problem on a mecool m8s pro w. You Can try this : go to your Android settings / applications / octoprint / permissions/ here you can revoke camera permission and will disable camera server. I found that camera server running always made app crash on my Android box. Feel free to tell if it works too for you

Thanks, after deleting permission octo severs has started normal way.

**Comment by alufers** [comment] 2022-10-06 23:42
Thanks for the workaround!

**Comment by alufers** [comment] 2022-10-06 23:47
Duplicate of #264

**Closed by alufers** 2022-10-06 23:47 UTC
Labels: camera-server
