### ISSUE TITLE
Octo4a Never installs

### ISSUE THREAD

**Issue by w7boz** [feelfreelinux/octo4a#282] opened 2022-09-22 12:13 UTC
Installation Corrupted - Always

**Comment by w7boz** [comment] 2022-09-22 12:27
Installation Corrupted
[octo4a.txt](https://github.com/feelfreelinux/octo4a/files/9625628/octo4a.txt)

**Comment by rfnovo** [comment] 2022-09-22 12:56
Same issue as https://github.com/feelfreelinux/octo4a/issues/281

**Comment by pnmartinez** [comment] 2022-09-22 14:52
Same here.
Xperia Z3, Android 5.

**Comment by lauripaulo** [comment] 2022-09-23 17:53
I seems to be a problem with Octoprint 1.8.3 dependencies. I am having the same issue. I was able to overcome this and install octoprint by fixing the version to 1.8.1 in the source code then compiling with Android Studio. Yes, dirty and ugly fix but at least I found the problem. 

I also harcoded the apk dependencies there while trying to make 1.8.3 works.

Hope it helps a proper fix in the code.

![image](https://user-images.githubusercontent.com/2783015/192027857-0c044619-98ce-46ad-8bf4-9cbaf60bb968.png)

**Comment by rfnovo** [comment] 2022-09-23 17:55
> I seems to be a problem with Octoprint 1.8.3 dependencies. I am having the same issue. I was able to overcome this and install octoprint by fixing the version to 1.8.1 in the source code then compiling with Android Studio. Yes, dirty and ugly fix but at least I found the problem.
> 
> I also harcoded the apk dependencies there while trying to make 1.8.3 works.
> 
> Hope it helps a proper fix in the code.
> 
> ![image](https://user-images.githubusercontent.com/2783015/192027857-0c044619-98ce-46ad-8bf4-9cbaf60bb968.png)

Mind share the APK?

**Comment by lauripaulo** [comment] 2022-09-23 18:08
> > I seems to be a problem with Octoprint 1.8.3 dependencies. I am having the same issue. I was able to overcome this and install octoprint by fixing the version to 1.8.1 in the source code then compiling with Android Studio. Yes, dirty and ugly fix but at least I found the problem.
> > I also harcoded the apk dependencies there while trying to make 1.8.3 works.
> > Hope it helps a proper fix in the code.
> > ![image](https://user-images.githubusercontent.com/2783015/192027857-0c044619-98ce-46ad-8bf4-9cbaf60bb968.png)
> 
> Mind share the APK?

I just compiled for me a "app-debug.apk" not a final or proper version. It's better to wait for the oficial fix. If you really want to test it, with all the problems it might have, let me know.

**Comment by w7boz** [comment] 2022-09-24 05:14
I would like to try it.

**Comment by pnmartinez** [comment] 2022-09-24 09:08
> > > I seems to be a problem with Octoprint 1.8.3 dependencies. I am having the same issue. I was able to overcome this and install octoprint by fixing the version to 1.8.1 in the source code then compiling with Android Studio. Yes, dirty and ugly fix but at least I found the problem.
> > > I also harcoded the apk dependencies there while trying to make 1.8.3 works.
> > > Hope it helps a proper fix in the code.
> > > ![image](https://user-images.githubusercontent.com/2783015/192027857-0c044619-98ce-46ad-8bf4-9cbaf60bb968.png)
> > 
> > 
> > Mind share the APK?
> 
> I just compiled for me a "app-debug.apk" not a final or proper version. It's better to wait for the oficial fix. If you really want to test it, with all the problems it might have, let me know.

Yeah! Another one interested on testing your APK here!

**Comment by fbreda** [comment] 2022-09-24 17:16
I would like to try it.

> > > I seems to be a problem with Octoprint 1.8.3 dependencies. I am having the same issue. I was able to overcome this and install octoprint by fixing the version to 1.8.1 in the source code then compiling with Android Studio. Yes, dirty and ugly fix but at least I found the problem.
> > > I also harcoded the apk dependencies there while trying to make 1.8.3 works.
> > > Hope it helps a proper fix in the code.
> > > ![image](https://user-images.githubusercontent.com/2783015/192027857-0c044619-98ce-46ad-8bf4-9cbaf60bb968.png)
> > 
> > 
> > Mind share the APK?
> 
> I just compiled for me a "app-debug.apk" not a final or proper version. It's better to wait for the oficial fix. If you really want to test it, with all the problems it might have, let me know.

I would like to try it, too

**Comment by protocold** [comment] 2022-09-25 07:39
ya could you please post your apk?

**Comment by lauripaulo** [comment] 2022-09-25 21:42
You can get an alpha release here:

https://github.com/lauripaulo/octo4a/releases/tag/octo4a-debug-fixed-octoprint-1.8.1

Please, use at your own risk. Upgrade to the official version when the problem is solved.

**Comment by ChrisIsCross** [comment] 2022-09-25 21:57
so i just installed your version and it works for the first time! thanks for the work!

**Comment by pnmartinez** [comment] 2022-09-26 07:12
> You can get an alpha release here:
> 
> https://github.com/lauripaulo/octo4a/releases/tag/octo4a-debug-fixed-octoprint-1.8.1
> 
> Please, use at your own risk. Upgrade to the official version when the problem is solved.

Here installed correctly too!

Only thing that crashes yet is **webcam support**, specifically when I try to set `Camera source` or `Camera resolution`.

**Comment by ss7admin** [comment] 2022-09-27 02:49
Thanks a lot. It worked

**Comment by w7boz** [comment] 2022-09-27 11:47
I just installed it and it worked! Ok, kind of... I enabled the Camera and it crashed. So I tried it again, and this time the Camera is working. Running a print right now. But can't wait to hook it up to the printer! I really love this APP!!!!

Kevin

**Comment by feelfreelinux** [comment] 2022-09-27 22:22
Fixed in https://github.com/feelfreelinux/octo4a/releases/tag/1.1.2 :)

**Closed by feelfreelinux** 2022-09-27 22:22 UTC
